#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 20
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 24

enum ts_symbol_identifiers {
  anon_sym_mod = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_pipe = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_func = 7,
  anon_sym_DASH_GT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  anon_sym_mut = 12,
  anon_sym_COLON = 13,
  anon_sym_let = 14,
  anon_sym_SEMI = 15,
  anon_sym_EQ = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_PERCENT = 21,
  anon_sym_COLON_COLON = 22,
  anon_sym_LT = 23,
  anon_sym_GT = 24,
  anon_sym_AMP = 25,
  anon_sym_const = 26,
  sym_identifier = 27,
  sym_number = 28,
  sym_comment = 29,
  sym_source_file = 30,
  sym__definition = 31,
  sym_module = 32,
  sym_pipeline = 33,
  sym_function = 34,
  sym_callSig = 35,
  sym_anonStructType = 36,
  sym_call = 37,
  sym_valueDef = 38,
  sym_memberInit = 39,
  sym_anonStruct = 40,
  sym_variableDefinition = 41,
  sym_pipelineStage = 42,
  sym_block = 43,
  sym_expression = 44,
  sym__binary_expression = 45,
  sym_assign = 46,
  sym_add = 47,
  sym_sub = 48,
  sym_mul = 49,
  sym_div = 50,
  sym_mod = 51,
  sym_scopedIdentifierSegment = 52,
  sym_scopedIdentifier = 53,
  sym_templateArguments = 54,
  sym_templateArgument = 55,
  sym_refOp = 56,
  sym_type = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_module_repeat1 = 59,
  aux_sym_pipeline_repeat1 = 60,
  aux_sym_anonStructType_repeat1 = 61,
  aux_sym_anonStruct_repeat1 = 62,
  aux_sym_block_repeat1 = 63,
  aux_sym_templateArguments_repeat1 = 64,
  aux_sym_type_repeat1 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_mod] = "mod",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_pipe] = "pipe",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_mut] = "mut",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_AMP] = "&",
  [anon_sym_const] = "const",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_module] = "module",
  [sym_pipeline] = "pipeline",
  [sym_function] = "function",
  [sym_callSig] = "callSig",
  [sym_anonStructType] = "anonStructType",
  [sym_call] = "call",
  [sym_valueDef] = "valueDef",
  [sym_memberInit] = "memberInit",
  [sym_anonStruct] = "anonStruct",
  [sym_variableDefinition] = "variableDefinition",
  [sym_pipelineStage] = "pipelineStage",
  [sym_block] = "block",
  [sym_expression] = "expression",
  [sym__binary_expression] = "_binary_expression",
  [sym_assign] = "assign",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_mod] = "mod",
  [sym_scopedIdentifierSegment] = "scopedIdentifierSegment",
  [sym_scopedIdentifier] = "scopedIdentifier",
  [sym_templateArguments] = "templateArguments",
  [sym_templateArgument] = "templateArgument",
  [sym_refOp] = "refOp",
  [sym_type] = "type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_pipeline_repeat1] = "pipeline_repeat1",
  [aux_sym_anonStructType_repeat1] = "anonStructType_repeat1",
  [aux_sym_anonStruct_repeat1] = "anonStruct_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_templateArguments_repeat1] = "templateArguments_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_pipe] = anon_sym_pipe,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_const] = anon_sym_const,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_module] = sym_module,
  [sym_pipeline] = sym_pipeline,
  [sym_function] = sym_function,
  [sym_callSig] = sym_callSig,
  [sym_anonStructType] = sym_anonStructType,
  [sym_call] = sym_call,
  [sym_valueDef] = sym_valueDef,
  [sym_memberInit] = sym_memberInit,
  [sym_anonStruct] = sym_anonStruct,
  [sym_variableDefinition] = sym_variableDefinition,
  [sym_pipelineStage] = sym_pipelineStage,
  [sym_block] = sym_block,
  [sym_expression] = sym_expression,
  [sym__binary_expression] = sym__binary_expression,
  [sym_assign] = sym_assign,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_mod] = sym_mod,
  [sym_scopedIdentifierSegment] = sym_scopedIdentifierSegment,
  [sym_scopedIdentifier] = sym_scopedIdentifier,
  [sym_templateArguments] = sym_templateArguments,
  [sym_templateArgument] = sym_templateArgument,
  [sym_refOp] = sym_refOp,
  [sym_type] = sym_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_pipeline_repeat1] = aux_sym_pipeline_repeat1,
  [aux_sym_anonStructType_repeat1] = aux_sym_anonStructType_repeat1,
  [aux_sym_anonStruct_repeat1] = aux_sym_anonStruct_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_templateArguments_repeat1] = aux_sym_templateArguments_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pipe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_pipeline] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_callSig] = {
    .visible = true,
    .named = true,
  },
  [sym_anonStructType] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_valueDef] = {
    .visible = true,
    .named = true,
  },
  [sym_memberInit] = {
    .visible = true,
    .named = true,
  },
  [sym_anonStruct] = {
    .visible = true,
    .named = true,
  },
  [sym_variableDefinition] = {
    .visible = true,
    .named = true,
  },
  [sym_pipelineStage] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__binary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_mod] = {
    .visible = true,
    .named = true,
  },
  [sym_scopedIdentifierSegment] = {
    .visible = true,
    .named = true,
  },
  [sym_scopedIdentifier] = {
    .visible = true,
    .named = true,
  },
  [sym_templateArguments] = {
    .visible = true,
    .named = true,
  },
  [sym_templateArgument] = {
    .visible = true,
    .named = true,
  },
  [sym_refOp] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipeline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_anonStructType_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_anonStruct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_templateArguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_callSig = 3,
  field_const = 4,
  field_def = 5,
  field_defs = 6,
  field_expressions = 7,
  field_func = 8,
  field_generic = 9,
  field_id = 10,
  field_input = 11,
  field_left = 12,
  field_mut = 13,
  field_output = 14,
  field_refOp = 15,
  field_return = 16,
  field_right = 17,
  field_stages = 18,
  field_type = 19,
  field_value = 20,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_callSig] = "callSig",
  [field_const] = "const",
  [field_def] = "def",
  [field_defs] = "defs",
  [field_expressions] = "expressions",
  [field_func] = "func",
  [field_generic] = "generic",
  [field_id] = "id",
  [field_input] = "input",
  [field_left] = "left",
  [field_mut] = "mut",
  [field_output] = "output",
  [field_refOp] = "refOp",
  [field_return] = "return",
  [field_right] = "right",
  [field_stages] = "stages",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 1},
  [11] = {.index = 15, .length = 1},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 2},
  [15] = {.index = 22, .length = 3},
  [16] = {.index = 25, .length = 1},
  [17] = {.index = 26, .length = 1},
  [18] = {.index = 27, .length = 2},
  [19] = {.index = 29, .length = 1},
  [20] = {.index = 30, .length = 3},
  [21] = {.index = 33, .length = 2},
  [22] = {.index = 35, .length = 2},
  [23] = {.index = 37, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
  [1] =
    {field_id, 0},
  [2] =
    {field_defs, 3},
    {field_id, 1},
  [4] =
    {field_input, 0},
  [5] =
    {field_generic, 1},
    {field_id, 0},
  [7] =
    {field_id, 1},
    {field_mut, 0},
  [9] =
    {field_callSig, 2},
    {field_id, 1},
  [11] =
    {field_body, 0},
  [12] =
    {field_input, 0},
    {field_output, 2},
  [14] =
    {field_mut, 1},
  [15] =
    {field_const, 1},
  [16] =
    {field_id, 1},
    {field_refOp, 0},
  [18] =
    {field_id, 0},
    {field_type, 2},
  [20] =
    {field_body, 1},
    {field_callSig, 0},
  [22] =
    {field_callSig, 2},
    {field_id, 1},
    {field_stages, 4},
  [25] =
    {field_def, 1},
  [26] =
    {field_return, 1},
  [27] =
    {field_args, 1},
    {field_func, 0},
  [29] =
    {field_expressions, 1},
  [30] =
    {field_id, 1},
    {field_mut, 0},
    {field_type, 3},
  [33] =
    {field_left, 0},
    {field_right, 2},
  [35] =
    {field_expressions, 1},
    {field_return, 2},
  [37] =
    {field_id, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '%', 59,
        '&', 63,
        '(', 44,
        ')', 46,
        '*', 57,
        '+', 54,
        ',', 45,
        '-', 56,
        '/', 58,
        ':', 49,
        ';', 52,
        '<', 61,
        '=', 53,
        '>', 62,
        '[', 40,
      );
      if (lookahead == '\\') SKIP(34);
      if (lookahead == ']') ADVANCE(41);
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(32);
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 'p') ADVANCE(22);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(10);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(10);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(11);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(11);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(13);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\r') SKIP(5);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(12);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '\r') SKIP(7);
      END_STATE();
    case 9:
      if (lookahead == '\r') ADVANCE(79);
      if (lookahead == '\\') ADVANCE(77);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        '%', 59,
        '(', 44,
        ')', 46,
        '*', 57,
        '+', 54,
        ',', 45,
        '-', 55,
        '/', 58,
        ':', 49,
        ';', 52,
        '<', 61,
        '=', 53,
        '>', 62,
      );
      if (lookahead == '\\') SKIP(2);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 11:
      if (lookahead == '&') ADVANCE(63);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '\\') SKIP(4);
      if (lookahead == '{') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 12:
      if (lookahead == '&') ADVANCE(63);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '\\') SKIP(8);
      if (lookahead == 'c') ADVANCE(68);
      if (lookahead == 'm') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 13:
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '\\') SKIP(6);
      if (lookahead == 'm') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 14:
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(78);
      END_STATE();
    case 15:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '/') ADVANCE(76);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 33:
      if (eof) ADVANCE(35);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_pipe);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_mut);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(60);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(78);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_const);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(79);
      if (lookahead == '\\') ADVANCE(77);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 10},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 10},
  [44] = {.lex_state = 10},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 11},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 11},
  [73] = {.lex_state = 11},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 13},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 13},
  [82] = {.lex_state = 11},
  [83] = {.lex_state = 11},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 11},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 11},
  [92] = {.lex_state = 11},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 11},
  [95] = {.lex_state = 11},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 11},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 11},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 11},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 11},
  [110] = {.lex_state = 11},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_pipe] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(112),
    [sym_module] = STATE(68),
    [aux_sym_source_file_repeat1] = STATE(68),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_mod] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_number,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(47), 1,
      sym_expression,
    STATE(79), 1,
      sym_memberInit,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [47] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(5), 1,
      aux_sym_block_repeat1,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(42), 1,
      sym_expression,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [94] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      aux_sym_block_repeat1,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(43), 1,
      sym_expression,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [141] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 1,
      anon_sym_let,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(36), 1,
      sym_number,
    STATE(5), 1,
      aux_sym_block_repeat1,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(48), 1,
      sym_expression,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [188] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(44), 1,
      sym_expression,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [229] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(18), 1,
      sym_expression,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [270] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(28), 1,
      sym_expression,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [311] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(29), 1,
      sym_expression,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [352] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(19), 1,
      sym_expression,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [393] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(23), 1,
      sym_expression,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [434] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(21), 1,
      sym_expression,
    STATE(39), 1,
      sym_anonStruct,
    STATE(40), 1,
      sym_call,
    STATE(41), 1,
      sym_scopedIdentifier,
    STATE(38), 8,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_mod,
  [475] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_SLASH,
    ACTIONS(43), 1,
      anon_sym_LT,
    STATE(17), 1,
      sym_templateArguments,
    ACTIONS(39), 12,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [502] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_SLASH,
    ACTIONS(45), 12,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [523] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(49), 12,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [544] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_SLASH,
    ACTIONS(57), 1,
      anon_sym_COLON_COLON,
    ACTIONS(53), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_GT,
  [567] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_SLASH,
    ACTIONS(59), 12,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [588] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    STATE(34), 1,
      sym_anonStruct,
    ACTIONS(63), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [622] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    STATE(34), 1,
      sym_anonStruct,
    ACTIONS(79), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [644] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(83), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_GT,
  [664] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_SLASH,
    STATE(34), 1,
      sym_anonStruct,
    ACTIONS(87), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [686] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_COLON,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(91), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [708] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    STATE(34), 1,
      sym_anonStruct,
    ACTIONS(97), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [730] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(101), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_GT,
  [750] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_SLASH,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(105), 1,
      anon_sym_COLON,
    STATE(17), 1,
      sym_templateArguments,
    ACTIONS(39), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_COLON_COLON,
  [776] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_SLASH,
    ACTIONS(107), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_GT,
  [796] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(115), 1,
      anon_sym_SLASH,
    ACTIONS(111), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [818] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    STATE(34), 1,
      sym_anonStruct,
    ACTIONS(117), 8,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [844] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    STATE(34), 1,
      sym_anonStruct,
    ACTIONS(119), 8,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [870] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_SLASH,
    ACTIONS(121), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [889] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_SLASH,
    ACTIONS(125), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [908] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(129), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [927] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_SLASH,
    ACTIONS(133), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [946] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(137), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [965] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_SLASH,
    ACTIONS(141), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [984] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_SLASH,
    ACTIONS(145), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1003] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_SLASH,
    ACTIONS(149), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_SLASH,
    ACTIONS(153), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1041] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_SLASH,
    ACTIONS(153), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1060] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_SLASH,
    ACTIONS(153), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1079] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_SLASH,
    ACTIONS(153), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1098] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    STATE(34), 1,
      sym_anonStruct,
  [1132] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      sym_anonStruct,
  [1166] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    STATE(34), 1,
      sym_anonStruct,
    ACTIONS(163), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1198] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    ACTIONS(167), 1,
      anon_sym_pipe,
    ACTIONS(169), 1,
      anon_sym_func,
    STATE(49), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [1221] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(167), 1,
      anon_sym_pipe,
    ACTIONS(169), 1,
      anon_sym_func,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(45), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [1244] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_anonStruct,
  [1275] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(77), 1,
      anon_sym_PERCENT,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    STATE(34), 1,
      sym_anonStruct,
  [1306] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_mod,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(180), 1,
      anon_sym_pipe,
    ACTIONS(183), 1,
      anon_sym_func,
    STATE(49), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [1329] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    ACTIONS(188), 1,
      anon_sym_RBRACK,
    ACTIONS(190), 1,
      anon_sym_LPAREN,
    STATE(88), 1,
      sym_block,
    STATE(92), 1,
      sym_anonStructType,
    STATE(96), 1,
      sym_callSig,
    STATE(53), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1355] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_LBRACE,
    ACTIONS(195), 1,
      anon_sym_RBRACK,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(88), 1,
      sym_block,
    STATE(92), 1,
      sym_anonStructType,
    STATE(96), 1,
      sym_callSig,
    STATE(51), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1381] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_AMP,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(26), 1,
      sym_scopedIdentifier,
    STATE(103), 1,
      sym_type,
    STATE(105), 1,
      sym_templateArgument,
    STATE(61), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1407] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    ACTIONS(190), 1,
      anon_sym_LPAREN,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      sym_block,
    STATE(92), 1,
      sym_anonStructType,
    STATE(96), 1,
      sym_callSig,
    STATE(51), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1433] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_AMP,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(26), 1,
      sym_scopedIdentifier,
    STATE(84), 1,
      sym_templateArgument,
    STATE(103), 1,
      sym_type,
    STATE(61), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1485] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1498] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_AMP,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(26), 1,
      sym_scopedIdentifier,
    STATE(37), 1,
      sym_type,
    STATE(61), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1534] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_AMP,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(26), 1,
      sym_scopedIdentifier,
    STATE(36), 1,
      sym_type,
    STATE(61), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1557] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_AMP,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(20), 1,
      sym_scopedIdentifier,
    STATE(72), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1577] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      anon_sym_let,
      sym_identifier,
    ACTIONS(25), 3,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
  [1590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 5,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1601] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 5,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1612] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(222), 1,
      anon_sym_mut,
    ACTIONS(224), 1,
      sym_identifier,
    STATE(87), 1,
      sym_valueDef,
  [1628] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_mut,
    ACTIONS(228), 1,
      anon_sym_AMP,
    ACTIONS(230), 1,
      anon_sym_const,
    ACTIONS(232), 1,
      sym_identifier,
  [1644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1654] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
    STATE(70), 2,
      sym_module,
      aux_sym_source_file_repeat1,
  [1668] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1678] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
    ACTIONS(242), 1,
      anon_sym_mod,
    STATE(70), 2,
      sym_module,
      aux_sym_source_file_repeat1,
  [1692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1702] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_AMP,
    ACTIONS(250), 1,
      sym_identifier,
    STATE(72), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1716] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(252), 1,
      sym_identifier,
    STATE(79), 1,
      sym_memberInit,
  [1729] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_LPAREN,
    STATE(92), 1,
      sym_anonStructType,
    STATE(97), 1,
      sym_callSig,
  [1742] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
  [1751] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_COMMA,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_anonStruct_repeat1,
  [1764] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_mut,
    ACTIONS(224), 1,
      sym_identifier,
    STATE(99), 1,
      sym_valueDef,
  [1777] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_GT,
    STATE(78), 1,
      aux_sym_templateArguments_repeat1,
  [1790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_anonStruct_repeat1,
  [1803] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_GT,
    STATE(78), 1,
      aux_sym_templateArguments_repeat1,
  [1816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_mut,
    ACTIONS(224), 1,
      sym_identifier,
    STATE(30), 1,
      sym_valueDef,
  [1829] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(16), 1,
      sym_scopedIdentifierSegment,
    STATE(74), 1,
      sym_scopedIdentifier,
  [1842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1851] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_GT,
    STATE(80), 1,
      aux_sym_templateArguments_repeat1,
  [1864] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_LPAREN,
    STATE(92), 1,
      sym_anonStructType,
    STATE(106), 1,
      sym_callSig,
  [1877] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_anonStructType_repeat1,
  [1890] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_anonStructType_repeat1,
  [1903] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
  [1912] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1921] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_anonStruct_repeat1,
  [1934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1943] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_DASH_GT,
    ACTIONS(295), 2,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1954] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_anonStructType_repeat1,
  [1967] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(24), 1,
      sym_scopedIdentifierSegment,
  [1977] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_identifier,
    STATE(104), 1,
      sym_memberInit,
  [1987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    STATE(75), 1,
      sym_block,
  [1997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym_block,
  [2007] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_LPAREN,
    STATE(101), 1,
      sym_anonStructType,
  [2017] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 2,
      anon_sym_AMP,
      sym_identifier,
  [2033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 2,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [2041] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 2,
      anon_sym_AMP,
      sym_identifier,
  [2049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [2057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [2073] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_LBRACK,
  [2080] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      sym_identifier,
  [2087] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_COLON,
  [2094] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym_identifier,
  [2101] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      sym_identifier,
  [2108] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_LBRACE,
  [2115] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 188,
  [SMALL_STATE(7)] = 229,
  [SMALL_STATE(8)] = 270,
  [SMALL_STATE(9)] = 311,
  [SMALL_STATE(10)] = 352,
  [SMALL_STATE(11)] = 393,
  [SMALL_STATE(12)] = 434,
  [SMALL_STATE(13)] = 475,
  [SMALL_STATE(14)] = 502,
  [SMALL_STATE(15)] = 523,
  [SMALL_STATE(16)] = 544,
  [SMALL_STATE(17)] = 567,
  [SMALL_STATE(18)] = 588,
  [SMALL_STATE(19)] = 622,
  [SMALL_STATE(20)] = 644,
  [SMALL_STATE(21)] = 664,
  [SMALL_STATE(22)] = 686,
  [SMALL_STATE(23)] = 708,
  [SMALL_STATE(24)] = 730,
  [SMALL_STATE(25)] = 750,
  [SMALL_STATE(26)] = 776,
  [SMALL_STATE(27)] = 796,
  [SMALL_STATE(28)] = 818,
  [SMALL_STATE(29)] = 844,
  [SMALL_STATE(30)] = 870,
  [SMALL_STATE(31)] = 889,
  [SMALL_STATE(32)] = 908,
  [SMALL_STATE(33)] = 927,
  [SMALL_STATE(34)] = 946,
  [SMALL_STATE(35)] = 965,
  [SMALL_STATE(36)] = 984,
  [SMALL_STATE(37)] = 1003,
  [SMALL_STATE(38)] = 1022,
  [SMALL_STATE(39)] = 1041,
  [SMALL_STATE(40)] = 1060,
  [SMALL_STATE(41)] = 1079,
  [SMALL_STATE(42)] = 1098,
  [SMALL_STATE(43)] = 1132,
  [SMALL_STATE(44)] = 1166,
  [SMALL_STATE(45)] = 1198,
  [SMALL_STATE(46)] = 1221,
  [SMALL_STATE(47)] = 1244,
  [SMALL_STATE(48)] = 1275,
  [SMALL_STATE(49)] = 1306,
  [SMALL_STATE(50)] = 1329,
  [SMALL_STATE(51)] = 1355,
  [SMALL_STATE(52)] = 1381,
  [SMALL_STATE(53)] = 1407,
  [SMALL_STATE(54)] = 1433,
  [SMALL_STATE(55)] = 1459,
  [SMALL_STATE(56)] = 1472,
  [SMALL_STATE(57)] = 1485,
  [SMALL_STATE(58)] = 1498,
  [SMALL_STATE(59)] = 1521,
  [SMALL_STATE(60)] = 1534,
  [SMALL_STATE(61)] = 1557,
  [SMALL_STATE(62)] = 1577,
  [SMALL_STATE(63)] = 1590,
  [SMALL_STATE(64)] = 1601,
  [SMALL_STATE(65)] = 1612,
  [SMALL_STATE(66)] = 1628,
  [SMALL_STATE(67)] = 1644,
  [SMALL_STATE(68)] = 1654,
  [SMALL_STATE(69)] = 1668,
  [SMALL_STATE(70)] = 1678,
  [SMALL_STATE(71)] = 1692,
  [SMALL_STATE(72)] = 1702,
  [SMALL_STATE(73)] = 1716,
  [SMALL_STATE(74)] = 1729,
  [SMALL_STATE(75)] = 1742,
  [SMALL_STATE(76)] = 1751,
  [SMALL_STATE(77)] = 1764,
  [SMALL_STATE(78)] = 1777,
  [SMALL_STATE(79)] = 1790,
  [SMALL_STATE(80)] = 1803,
  [SMALL_STATE(81)] = 1816,
  [SMALL_STATE(82)] = 1829,
  [SMALL_STATE(83)] = 1842,
  [SMALL_STATE(84)] = 1851,
  [SMALL_STATE(85)] = 1864,
  [SMALL_STATE(86)] = 1877,
  [SMALL_STATE(87)] = 1890,
  [SMALL_STATE(88)] = 1903,
  [SMALL_STATE(89)] = 1912,
  [SMALL_STATE(90)] = 1921,
  [SMALL_STATE(91)] = 1934,
  [SMALL_STATE(92)] = 1943,
  [SMALL_STATE(93)] = 1954,
  [SMALL_STATE(94)] = 1967,
  [SMALL_STATE(95)] = 1977,
  [SMALL_STATE(96)] = 1987,
  [SMALL_STATE(97)] = 1997,
  [SMALL_STATE(98)] = 2007,
  [SMALL_STATE(99)] = 2017,
  [SMALL_STATE(100)] = 2025,
  [SMALL_STATE(101)] = 2033,
  [SMALL_STATE(102)] = 2041,
  [SMALL_STATE(103)] = 2049,
  [SMALL_STATE(104)] = 2057,
  [SMALL_STATE(105)] = 2065,
  [SMALL_STATE(106)] = 2073,
  [SMALL_STATE(107)] = 2080,
  [SMALL_STATE(108)] = 2087,
  [SMALL_STATE(109)] = 2094,
  [SMALL_STATE(110)] = 2101,
  [SMALL_STATE(111)] = 2108,
  [SMALL_STATE(112)] = 2115,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifierSegment, 1, 0, 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifierSegment, 1, 0, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArguments, 4, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_templateArguments, 4, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArguments, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_templateArguments, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifier, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifier, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifierSegment, 2, 0, 5),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifierSegment, 2, 0, 5),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 21),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3, 0, 21),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul, 3, 0, 21),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 12),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 2, 0, 12),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod, 3, 0, 21),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mod, 3, 0, 21),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 2, 0, 6),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 2, 0, 6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 21),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 21),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifier, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifier, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 1, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 1, 0, 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 21),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, 0, 21),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variableDefinition, 2, 0, 16),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variableDefinition, 2, 0, 16),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 18),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 18),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 4, 0, 20),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 4, 0, 20),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 3, 0, 13),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 3, 0, 13),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memberInit, 3, 0, 23),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 22),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 17),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 19),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 4, 0, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 5, 0, 3),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_refOp, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_refOp, 1, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 5, 0, 7),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 6, 0, 15),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipelineStage, 2, 0, 14),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_anonStruct_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_anonStruct_repeat1, 2, 0, 0),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templateArguments_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_templateArguments_repeat1, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 4, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_anonStructType_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_anonStructType_repeat1, 2, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipelineStage, 1, 0, 8),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 2, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 3, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callSig, 1, 0, 4),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_refOp, 2, 0, 10),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callSig, 3, 0, 9),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_refOp, 2, 0, 11),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArgument, 1, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [321] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_branescript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
