#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 107
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 19
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 23

enum ts_symbol_identifiers {
  anon_sym_mod = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_pipe = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_func = 7,
  anon_sym_DASH_GT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  anon_sym_mut = 12,
  anon_sym_COLON = 13,
  anon_sym_let = 14,
  anon_sym_SEMI = 15,
  anon_sym_EQ = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_COLON_COLON = 21,
  anon_sym_LT = 22,
  anon_sym_GT = 23,
  anon_sym_AMP = 24,
  anon_sym_const = 25,
  sym_identifier = 26,
  sym_number = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym__definition = 30,
  sym_module = 31,
  sym_pipeline = 32,
  sym_function = 33,
  sym_callSig = 34,
  sym_anonStructType = 35,
  sym_call = 36,
  sym_valueDef = 37,
  sym_memberInit = 38,
  sym_anonStruct = 39,
  sym_variableDefinition = 40,
  sym_pipelineStage = 41,
  sym_block = 42,
  sym__expression = 43,
  sym__binary_expression = 44,
  sym_assign = 45,
  sym_add = 46,
  sym_sub = 47,
  sym_mul = 48,
  sym_div = 49,
  sym_scopedIdentifier = 50,
  sym_templateArguments = 51,
  sym_templateArgument = 52,
  sym_type = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_module_repeat1 = 55,
  aux_sym_pipeline_repeat1 = 56,
  aux_sym_anonStructType_repeat1 = 57,
  aux_sym_anonStruct_repeat1 = 58,
  aux_sym_block_repeat1 = 59,
  aux_sym_templateArguments_repeat1 = 60,
  aux_sym_type_repeat1 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_mod] = "mod",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_pipe] = "pipe",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_mut] = "mut",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_AMP] = "&",
  [anon_sym_const] = "const",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_module] = "module",
  [sym_pipeline] = "pipeline",
  [sym_function] = "function",
  [sym_callSig] = "callSig",
  [sym_anonStructType] = "anonStructType",
  [sym_call] = "call",
  [sym_valueDef] = "valueDef",
  [sym_memberInit] = "memberInit",
  [sym_anonStruct] = "anonStruct",
  [sym_variableDefinition] = "variableDefinition",
  [sym_pipelineStage] = "pipelineStage",
  [sym_block] = "block",
  [sym__expression] = "_expression",
  [sym__binary_expression] = "_binary_expression",
  [sym_assign] = "assign",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_scopedIdentifier] = "scopedIdentifier",
  [sym_templateArguments] = "templateArguments",
  [sym_templateArgument] = "templateArgument",
  [sym_type] = "type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_pipeline_repeat1] = "pipeline_repeat1",
  [aux_sym_anonStructType_repeat1] = "anonStructType_repeat1",
  [aux_sym_anonStruct_repeat1] = "anonStruct_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_templateArguments_repeat1] = "templateArguments_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_pipe] = anon_sym_pipe,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_const] = anon_sym_const,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_module] = sym_module,
  [sym_pipeline] = sym_pipeline,
  [sym_function] = sym_function,
  [sym_callSig] = sym_callSig,
  [sym_anonStructType] = sym_anonStructType,
  [sym_call] = sym_call,
  [sym_valueDef] = sym_valueDef,
  [sym_memberInit] = sym_memberInit,
  [sym_anonStruct] = sym_anonStruct,
  [sym_variableDefinition] = sym_variableDefinition,
  [sym_pipelineStage] = sym_pipelineStage,
  [sym_block] = sym_block,
  [sym__expression] = sym__expression,
  [sym__binary_expression] = sym__binary_expression,
  [sym_assign] = sym_assign,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_scopedIdentifier] = sym_scopedIdentifier,
  [sym_templateArguments] = sym_templateArguments,
  [sym_templateArgument] = sym_templateArgument,
  [sym_type] = sym_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_pipeline_repeat1] = aux_sym_pipeline_repeat1,
  [aux_sym_anonStructType_repeat1] = aux_sym_anonStructType_repeat1,
  [aux_sym_anonStruct_repeat1] = aux_sym_anonStruct_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_templateArguments_repeat1] = aux_sym_templateArguments_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pipe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_pipeline] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_callSig] = {
    .visible = true,
    .named = true,
  },
  [sym_anonStructType] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_valueDef] = {
    .visible = true,
    .named = true,
  },
  [sym_memberInit] = {
    .visible = true,
    .named = true,
  },
  [sym_anonStruct] = {
    .visible = true,
    .named = true,
  },
  [sym_variableDefinition] = {
    .visible = true,
    .named = true,
  },
  [sym_pipelineStage] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__binary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_scopedIdentifier] = {
    .visible = true,
    .named = true,
  },
  [sym_templateArguments] = {
    .visible = true,
    .named = true,
  },
  [sym_templateArgument] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipeline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_anonStructType_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_anonStruct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_templateArguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_callSig = 3,
  field_child = 4,
  field_def = 5,
  field_defs = 6,
  field_expressions = 7,
  field_func = 8,
  field_id = 9,
  field_input = 10,
  field_left = 11,
  field_mut = 12,
  field_output = 13,
  field_return = 14,
  field_right = 15,
  field_stages = 16,
  field_templateArgs = 17,
  field_type = 18,
  field_value = 19,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_callSig] = "callSig",
  [field_child] = "child",
  [field_def] = "def",
  [field_defs] = "defs",
  [field_expressions] = "expressions",
  [field_func] = "func",
  [field_id] = "id",
  [field_input] = "input",
  [field_left] = "left",
  [field_mut] = "mut",
  [field_output] = "output",
  [field_return] = "return",
  [field_right] = "right",
  [field_stages] = "stages",
  [field_templateArgs] = "templateArgs",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 1},
  [11] = {.index = 17, .length = 2},
  [12] = {.index = 19, .length = 2},
  [13] = {.index = 21, .length = 2},
  [14] = {.index = 23, .length = 3},
  [15] = {.index = 26, .length = 1},
  [16] = {.index = 27, .length = 1},
  [17] = {.index = 28, .length = 2},
  [18] = {.index = 30, .length = 1},
  [19] = {.index = 31, .length = 3},
  [20] = {.index = 34, .length = 2},
  [21] = {.index = 36, .length = 2},
  [22] = {.index = 38, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
  [1] =
    {field_id, 0},
  [2] =
    {field_templateArgs, 0},
  [3] =
    {field_defs, 3},
    {field_id, 1},
  [5] =
    {field_input, 0},
  [6] =
    {field_child, 1},
    {field_child, 2},
    {field_id, 0},
  [9] =
    {field_child, 1},
    {field_child, 2},
    {field_templateArgs, 0},
  [12] =
    {field_id, 1},
    {field_mut, 0},
  [14] =
    {field_callSig, 2},
    {field_id, 1},
  [16] =
    {field_body, 0},
  [17] =
    {field_input, 0},
    {field_output, 2},
  [19] =
    {field_id, 0},
    {field_type, 2},
  [21] =
    {field_body, 1},
    {field_callSig, 0},
  [23] =
    {field_callSig, 2},
    {field_id, 1},
    {field_stages, 4},
  [26] =
    {field_def, 1},
  [27] =
    {field_return, 1},
  [28] =
    {field_args, 1},
    {field_func, 0},
  [30] =
    {field_expressions, 1},
  [31] =
    {field_id, 1},
    {field_mut, 0},
    {field_type, 3},
  [34] =
    {field_left, 0},
    {field_right, 2},
  [36] =
    {field_expressions, 1},
    {field_return, 2},
  [38] =
    {field_id, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '&', 62,
        '(', 44,
        ')', 46,
        '*', 57,
        '+', 54,
        ',', 45,
        '-', 56,
        '/', 58,
        ':', 49,
        ';', 52,
        '<', 60,
        '=', 53,
        '>', 61,
        '[', 40,
      );
      if (lookahead == '\\') SKIP(34);
      if (lookahead == ']') ADVANCE(41);
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(32);
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 'p') ADVANCE(22);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(12);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(10);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(10);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(11);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(11);
      if (lookahead == '\r') SKIP(5);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(13);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\r') SKIP(7);
      END_STATE();
    case 9:
      if (lookahead == '\r') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(76);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    case 10:
      if (lookahead == '&') ADVANCE(62);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '<') ADVANCE(60);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '\\') SKIP(4);
      if (lookahead == '{') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 11:
      if (lookahead == '&') ADVANCE(62);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '<') ADVANCE(60);
      if (lookahead == '\\') SKIP(6);
      if (lookahead == 'c') ADVANCE(67);
      if (lookahead == 'm') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        '(', 44,
        ')', 46,
        '*', 57,
        '+', 54,
        ',', 45,
        '-', 55,
        '/', 58,
        ':', 49,
        ';', 52,
        '<', 60,
        '=', 53,
        '>', 61,
      );
      if (lookahead == '\\') SKIP(2);
      if (lookahead == 'l') ADVANCE(65);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 13:
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '\\') SKIP(8);
      if (lookahead == 'm') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 14:
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(77);
      END_STATE();
    case 15:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '/') ADVANCE(75);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 33:
      if (eof) ADVANCE(35);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_pipe);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_mut);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(77);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_const);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(76);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 12},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 12},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 10},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 11},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 13},
  [63] = {.lex_state = 10},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 10},
  [67] = {.lex_state = 10},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 10},
  [77] = {.lex_state = 13},
  [78] = {.lex_state = 10},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 10},
  [83] = {.lex_state = 13},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 10},
  [86] = {.lex_state = 10},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 10},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 10},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 10},
  [103] = {.lex_state = 10},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 10},
  [106] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_pipe] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(106),
    [sym_module] = STATE(64),
    [aux_sym_source_file_repeat1] = STATE(64),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_mod] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_RBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_number,
    STATE(5), 1,
      aux_sym_block_repeat1,
    STATE(12), 1,
      sym_templateArguments,
    STATE(37), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [41] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_RPAREN,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_number,
    STATE(12), 1,
      sym_templateArguments,
    STATE(74), 1,
      sym_memberInit,
    STATE(47), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [82] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 1,
      sym_number,
    STATE(2), 1,
      aux_sym_block_repeat1,
    STATE(12), 1,
      sym_templateArguments,
    STATE(36), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [123] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(36), 1,
      anon_sym_let,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_number,
    STATE(5), 1,
      aux_sym_block_repeat1,
    STATE(12), 1,
      sym_templateArguments,
    STATE(45), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [164] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym_number,
    STATE(12), 1,
      sym_templateArguments,
    STATE(19), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [199] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_number,
    STATE(12), 1,
      sym_templateArguments,
    STATE(18), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [234] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(52), 1,
      sym_number,
    STATE(12), 1,
      sym_templateArguments,
    STATE(24), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [269] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(54), 1,
      sym_number,
    STATE(12), 1,
      sym_templateArguments,
    STATE(23), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [304] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(56), 1,
      sym_number,
    STATE(12), 1,
      sym_templateArguments,
    STATE(21), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [339] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_number,
    STATE(12), 1,
      sym_templateArguments,
    STATE(39), 11,
      sym_call,
      sym_anonStruct,
      sym_variableDefinition,
      sym__expression,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_scopedIdentifier,
  [374] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_SLASH,
    ACTIONS(64), 1,
      anon_sym_COLON_COLON,
    ACTIONS(60), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [396] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(66), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [416] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_SLASH,
    ACTIONS(70), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [436] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_SLASH,
    ACTIONS(78), 1,
      anon_sym_COLON_COLON,
    ACTIONS(74), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [458] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_COLON,
    ACTIONS(84), 1,
      anon_sym_SLASH,
    ACTIONS(80), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [479] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_SLASH,
    ACTIONS(86), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [498] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      sym_anonStruct,
    ACTIONS(90), 8,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [521] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      anon_sym_EQ,
    ACTIONS(102), 1,
      anon_sym_PLUS,
    ACTIONS(104), 1,
      anon_sym_DASH,
    STATE(30), 1,
      sym_anonStruct,
    ACTIONS(96), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [552] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(106), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [571] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      sym_anonStruct,
    ACTIONS(110), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [592] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    ACTIONS(114), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [611] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      sym_anonStruct,
    ACTIONS(118), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [632] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      sym_anonStruct,
    ACTIONS(122), 8,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [655] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_SLASH,
    ACTIONS(124), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [674] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_COLON,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    ACTIONS(128), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [695] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_SLASH,
    ACTIONS(134), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [713] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_SLASH,
    ACTIONS(138), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [731] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_SLASH,
    ACTIONS(142), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [749] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_SLASH,
    ACTIONS(146), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [767] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_SLASH,
    ACTIONS(150), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [785] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_SLASH,
    ACTIONS(154), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_SLASH,
    ACTIONS(158), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [821] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    ACTIONS(162), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [839] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_mod,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      anon_sym_pipe,
    ACTIONS(174), 1,
      anon_sym_func,
    STATE(35), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [862] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      anon_sym_EQ,
    ACTIONS(102), 1,
      anon_sym_PLUS,
    ACTIONS(104), 1,
      anon_sym_DASH,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    ACTIONS(179), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      sym_anonStruct,
  [893] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      anon_sym_EQ,
    ACTIONS(102), 1,
      anon_sym_PLUS,
    ACTIONS(104), 1,
      anon_sym_DASH,
    ACTIONS(179), 1,
      anon_sym_SEMI,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym_anonStruct,
  [924] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(185), 1,
      anon_sym_pipe,
    ACTIONS(187), 1,
      anon_sym_func,
    STATE(40), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [947] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      anon_sym_EQ,
    ACTIONS(102), 1,
      anon_sym_PLUS,
    ACTIONS(104), 1,
      anon_sym_DASH,
    STATE(30), 1,
      sym_anonStruct,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [976] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(185), 1,
      anon_sym_pipe,
    ACTIONS(187), 1,
      anon_sym_func,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(35), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [999] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_SLASH,
    ACTIONS(78), 1,
      anon_sym_COLON_COLON,
    ACTIONS(193), 1,
      anon_sym_COLON,
    ACTIONS(74), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1020] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(195), 1,
      anon_sym_AMP,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(12), 1,
      sym_templateArguments,
    STATE(25), 1,
      sym_scopedIdentifier,
    STATE(56), 1,
      aux_sym_type_repeat1,
    STATE(93), 1,
      sym_type,
    STATE(95), 1,
      sym_templateArgument,
  [1048] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_block,
    STATE(88), 1,
      sym_anonStructType,
    STATE(96), 1,
      sym_callSig,
    STATE(48), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1074] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LBRACE,
    ACTIONS(208), 1,
      anon_sym_RBRACK,
    ACTIONS(210), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_block,
    STATE(88), 1,
      sym_anonStructType,
    STATE(96), 1,
      sym_callSig,
    STATE(44), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1100] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      anon_sym_EQ,
    ACTIONS(102), 1,
      anon_sym_PLUS,
    ACTIONS(104), 1,
      anon_sym_DASH,
    ACTIONS(179), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      sym_anonStruct,
  [1128] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(195), 1,
      anon_sym_AMP,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(12), 1,
      sym_templateArguments,
    STATE(25), 1,
      sym_scopedIdentifier,
    STATE(56), 1,
      aux_sym_type_repeat1,
    STATE(87), 1,
      sym_templateArgument,
    STATE(93), 1,
      sym_type,
  [1156] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(94), 1,
      anon_sym_SLASH,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      anon_sym_EQ,
    ACTIONS(102), 1,
      anon_sym_PLUS,
    ACTIONS(104), 1,
      anon_sym_DASH,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      sym_anonStruct,
  [1184] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      sym_block,
    STATE(88), 1,
      sym_anonStructType,
    STATE(96), 1,
      sym_callSig,
    STATE(44), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1210] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(195), 1,
      anon_sym_AMP,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(12), 1,
      sym_templateArguments,
    STATE(25), 1,
      sym_scopedIdentifier,
    STATE(34), 1,
      sym_type,
    STATE(56), 1,
      aux_sym_type_repeat1,
  [1235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1248] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(195), 1,
      anon_sym_AMP,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(12), 1,
      sym_templateArguments,
    STATE(25), 1,
      sym_scopedIdentifier,
    STATE(32), 1,
      sym_type,
    STATE(56), 1,
      aux_sym_type_repeat1,
  [1273] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1312] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_let,
      sym_identifier,
    ACTIONS(31), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LT,
      sym_number,
  [1326] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(195), 1,
      anon_sym_AMP,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(12), 1,
      sym_templateArguments,
    STATE(22), 1,
      sym_scopedIdentifier,
    STATE(67), 1,
      aux_sym_type_repeat1,
  [1348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 5,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1359] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 5,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1370] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
    ACTIONS(231), 2,
      anon_sym_mut,
      anon_sym_const,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_AMP,
  [1385] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(12), 1,
      sym_templateArguments,
    STATE(17), 1,
      sym_scopedIdentifier,
  [1401] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1411] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    ACTIONS(241), 1,
      anon_sym_mut,
    ACTIONS(243), 1,
      sym_identifier,
    STATE(84), 1,
      sym_valueDef,
  [1427] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(12), 1,
      sym_templateArguments,
    STATE(20), 1,
      sym_scopedIdentifier,
  [1443] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
    STATE(65), 2,
      sym_module,
      aux_sym_source_file_repeat1,
  [1457] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
    ACTIONS(249), 1,
      anon_sym_mod,
    STATE(65), 2,
      sym_module,
      aux_sym_source_file_repeat1,
  [1471] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(12), 1,
      sym_templateArguments,
    STATE(75), 1,
      sym_scopedIdentifier,
  [1487] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_AMP,
    STATE(67), 1,
      aux_sym_type_repeat1,
    ACTIONS(252), 2,
      anon_sym_LT,
      sym_identifier,
  [1501] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1521] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_anonStructType_repeat1,
  [1534] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
  [1543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
  [1552] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(88), 1,
      sym_anonStructType,
    STATE(100), 1,
      sym_callSig,
  [1565] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_anonStruct_repeat1,
  [1578] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(88), 1,
      sym_anonStructType,
    STATE(92), 1,
      sym_callSig,
  [1591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1600] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_mut,
    ACTIONS(243), 1,
      sym_identifier,
    STATE(97), 1,
      sym_valueDef,
  [1613] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_RPAREN,
    ACTIONS(275), 1,
      sym_identifier,
    STATE(74), 1,
      sym_memberInit,
  [1626] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(280), 1,
      anon_sym_GT,
    STATE(79), 1,
      aux_sym_templateArguments_repeat1,
  [1639] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_anonStructType_repeat1,
  [1652] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    ACTIONS(289), 1,
      anon_sym_GT,
    STATE(79), 1,
      aux_sym_templateArguments_repeat1,
  [1665] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 3,
      anon_sym_LT,
      anon_sym_AMP,
      sym_identifier,
  [1674] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_mut,
    ACTIONS(243), 1,
      sym_identifier,
    STATE(29), 1,
      sym_valueDef,
  [1687] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_anonStructType_repeat1,
  [1700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1718] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    ACTIONS(297), 1,
      anon_sym_GT,
    STATE(81), 1,
      aux_sym_templateArguments_repeat1,
  [1731] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_DASH_GT,
    ACTIONS(299), 2,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1742] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_anonStruct_repeat1,
  [1755] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_COMMA,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_anonStruct_repeat1,
  [1768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(99), 1,
      sym_anonStructType,
  [1778] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    STATE(68), 1,
      sym_block,
  [1788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1796] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_identifier,
    STATE(98), 1,
      sym_memberInit,
  [1806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_block,
  [1824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1832] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1840] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 2,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_LBRACK,
  [1855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_COLON,
  [1862] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      sym_identifier,
  [1869] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      sym_identifier,
  [1876] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_LBRACE,
  [1883] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_identifier,
  [1890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 164,
  [SMALL_STATE(7)] = 199,
  [SMALL_STATE(8)] = 234,
  [SMALL_STATE(9)] = 269,
  [SMALL_STATE(10)] = 304,
  [SMALL_STATE(11)] = 339,
  [SMALL_STATE(12)] = 374,
  [SMALL_STATE(13)] = 396,
  [SMALL_STATE(14)] = 416,
  [SMALL_STATE(15)] = 436,
  [SMALL_STATE(16)] = 458,
  [SMALL_STATE(17)] = 479,
  [SMALL_STATE(18)] = 498,
  [SMALL_STATE(19)] = 521,
  [SMALL_STATE(20)] = 552,
  [SMALL_STATE(21)] = 571,
  [SMALL_STATE(22)] = 592,
  [SMALL_STATE(23)] = 611,
  [SMALL_STATE(24)] = 632,
  [SMALL_STATE(25)] = 655,
  [SMALL_STATE(26)] = 674,
  [SMALL_STATE(27)] = 695,
  [SMALL_STATE(28)] = 713,
  [SMALL_STATE(29)] = 731,
  [SMALL_STATE(30)] = 749,
  [SMALL_STATE(31)] = 767,
  [SMALL_STATE(32)] = 785,
  [SMALL_STATE(33)] = 803,
  [SMALL_STATE(34)] = 821,
  [SMALL_STATE(35)] = 839,
  [SMALL_STATE(36)] = 862,
  [SMALL_STATE(37)] = 893,
  [SMALL_STATE(38)] = 924,
  [SMALL_STATE(39)] = 947,
  [SMALL_STATE(40)] = 976,
  [SMALL_STATE(41)] = 999,
  [SMALL_STATE(42)] = 1020,
  [SMALL_STATE(43)] = 1048,
  [SMALL_STATE(44)] = 1074,
  [SMALL_STATE(45)] = 1100,
  [SMALL_STATE(46)] = 1128,
  [SMALL_STATE(47)] = 1156,
  [SMALL_STATE(48)] = 1184,
  [SMALL_STATE(49)] = 1210,
  [SMALL_STATE(50)] = 1235,
  [SMALL_STATE(51)] = 1248,
  [SMALL_STATE(52)] = 1273,
  [SMALL_STATE(53)] = 1286,
  [SMALL_STATE(54)] = 1299,
  [SMALL_STATE(55)] = 1312,
  [SMALL_STATE(56)] = 1326,
  [SMALL_STATE(57)] = 1348,
  [SMALL_STATE(58)] = 1359,
  [SMALL_STATE(59)] = 1370,
  [SMALL_STATE(60)] = 1385,
  [SMALL_STATE(61)] = 1401,
  [SMALL_STATE(62)] = 1411,
  [SMALL_STATE(63)] = 1427,
  [SMALL_STATE(64)] = 1443,
  [SMALL_STATE(65)] = 1457,
  [SMALL_STATE(66)] = 1471,
  [SMALL_STATE(67)] = 1487,
  [SMALL_STATE(68)] = 1501,
  [SMALL_STATE(69)] = 1511,
  [SMALL_STATE(70)] = 1521,
  [SMALL_STATE(71)] = 1534,
  [SMALL_STATE(72)] = 1543,
  [SMALL_STATE(73)] = 1552,
  [SMALL_STATE(74)] = 1565,
  [SMALL_STATE(75)] = 1578,
  [SMALL_STATE(76)] = 1591,
  [SMALL_STATE(77)] = 1600,
  [SMALL_STATE(78)] = 1613,
  [SMALL_STATE(79)] = 1626,
  [SMALL_STATE(80)] = 1639,
  [SMALL_STATE(81)] = 1652,
  [SMALL_STATE(82)] = 1665,
  [SMALL_STATE(83)] = 1674,
  [SMALL_STATE(84)] = 1687,
  [SMALL_STATE(85)] = 1700,
  [SMALL_STATE(86)] = 1709,
  [SMALL_STATE(87)] = 1718,
  [SMALL_STATE(88)] = 1731,
  [SMALL_STATE(89)] = 1742,
  [SMALL_STATE(90)] = 1755,
  [SMALL_STATE(91)] = 1768,
  [SMALL_STATE(92)] = 1778,
  [SMALL_STATE(93)] = 1788,
  [SMALL_STATE(94)] = 1796,
  [SMALL_STATE(95)] = 1806,
  [SMALL_STATE(96)] = 1814,
  [SMALL_STATE(97)] = 1824,
  [SMALL_STATE(98)] = 1832,
  [SMALL_STATE(99)] = 1840,
  [SMALL_STATE(100)] = 1848,
  [SMALL_STATE(101)] = 1855,
  [SMALL_STATE(102)] = 1862,
  [SMALL_STATE(103)] = 1869,
  [SMALL_STATE(104)] = 1876,
  [SMALL_STATE(105)] = 1883,
  [SMALL_STATE(106)] = 1890,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifier, 1, 0, 3),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifier, 1, 0, 3),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArguments, 4, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_templateArguments, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArguments, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_templateArguments, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifier, 1, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifier, 1, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 2, 0, 8),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 2, 0, 8),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifier, 3, 0, 6),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifier, 3, 0, 6),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 20),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 20),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifier, 3, 0, 7),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifier, 3, 0, 7),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 20),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 20),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3, 0, 20),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul, 3, 0, 20),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, 0, 20),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 1, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 1, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variableDefinition, 2, 0, 15),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variableDefinition, 2, 0, 15),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 17),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 17),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 4, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 4, 0, 19),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 4, 0, 19),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 3, 0, 12),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 3, 0, 12),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memberInit, 3, 0, 22),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 16),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 21),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 18),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 5, 0, 4),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 4, 0, 1),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 1, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_type_repeat1, 1, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 6, 0, 14),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 5, 0, 9),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipelineStage, 2, 0, 13),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipelineStage, 1, 0, 10),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 3, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templateArguments_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_templateArguments_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_anonStructType_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_anonStructType_repeat1, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 2, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 4, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callSig, 1, 0, 5),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [305] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_anonStruct_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_anonStruct_repeat1, 2, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArgument, 1, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callSig, 3, 0, 11),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [326] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_branescript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
