#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 20
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 24

enum ts_symbol_identifiers {
  anon_sym_mod = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_pipe = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_func = 7,
  anon_sym_DASH_GT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  anon_sym_mut = 12,
  anon_sym_COLON = 13,
  anon_sym_let = 14,
  anon_sym_SEMI = 15,
  anon_sym_EQ = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_COLON_COLON = 21,
  anon_sym_LT = 22,
  anon_sym_GT = 23,
  anon_sym_AMP = 24,
  anon_sym_const = 25,
  sym_identifier = 26,
  sym_number = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym__definition = 30,
  sym_module = 31,
  sym_pipeline = 32,
  sym_function = 33,
  sym_callSig = 34,
  sym_anonStructType = 35,
  sym_call = 36,
  sym_valueDef = 37,
  sym_memberInit = 38,
  sym_anonStruct = 39,
  sym_variableDefinition = 40,
  sym_pipelineStage = 41,
  sym_block = 42,
  sym_expression = 43,
  sym__binary_expression = 44,
  sym_assign = 45,
  sym_add = 46,
  sym_sub = 47,
  sym_mul = 48,
  sym_div = 49,
  sym_scopedIdentifierSegment = 50,
  sym_scopedIdentifier = 51,
  sym_templateArguments = 52,
  sym_templateArgument = 53,
  sym_refOp = 54,
  sym_type = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_module_repeat1 = 57,
  aux_sym_pipeline_repeat1 = 58,
  aux_sym_anonStructType_repeat1 = 59,
  aux_sym_anonStruct_repeat1 = 60,
  aux_sym_block_repeat1 = 61,
  aux_sym_templateArguments_repeat1 = 62,
  aux_sym_type_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_mod] = "mod",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_pipe] = "pipe",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_mut] = "mut",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_AMP] = "&",
  [anon_sym_const] = "const",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_module] = "module",
  [sym_pipeline] = "pipeline",
  [sym_function] = "function",
  [sym_callSig] = "callSig",
  [sym_anonStructType] = "anonStructType",
  [sym_call] = "call",
  [sym_valueDef] = "valueDef",
  [sym_memberInit] = "memberInit",
  [sym_anonStruct] = "anonStruct",
  [sym_variableDefinition] = "variableDefinition",
  [sym_pipelineStage] = "pipelineStage",
  [sym_block] = "block",
  [sym_expression] = "expression",
  [sym__binary_expression] = "_binary_expression",
  [sym_assign] = "assign",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_scopedIdentifierSegment] = "scopedIdentifierSegment",
  [sym_scopedIdentifier] = "scopedIdentifier",
  [sym_templateArguments] = "templateArguments",
  [sym_templateArgument] = "templateArgument",
  [sym_refOp] = "refOp",
  [sym_type] = "type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_pipeline_repeat1] = "pipeline_repeat1",
  [aux_sym_anonStructType_repeat1] = "anonStructType_repeat1",
  [aux_sym_anonStruct_repeat1] = "anonStruct_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_templateArguments_repeat1] = "templateArguments_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_pipe] = anon_sym_pipe,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_const] = anon_sym_const,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_module] = sym_module,
  [sym_pipeline] = sym_pipeline,
  [sym_function] = sym_function,
  [sym_callSig] = sym_callSig,
  [sym_anonStructType] = sym_anonStructType,
  [sym_call] = sym_call,
  [sym_valueDef] = sym_valueDef,
  [sym_memberInit] = sym_memberInit,
  [sym_anonStruct] = sym_anonStruct,
  [sym_variableDefinition] = sym_variableDefinition,
  [sym_pipelineStage] = sym_pipelineStage,
  [sym_block] = sym_block,
  [sym_expression] = sym_expression,
  [sym__binary_expression] = sym__binary_expression,
  [sym_assign] = sym_assign,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_scopedIdentifierSegment] = sym_scopedIdentifierSegment,
  [sym_scopedIdentifier] = sym_scopedIdentifier,
  [sym_templateArguments] = sym_templateArguments,
  [sym_templateArgument] = sym_templateArgument,
  [sym_refOp] = sym_refOp,
  [sym_type] = sym_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_pipeline_repeat1] = aux_sym_pipeline_repeat1,
  [aux_sym_anonStructType_repeat1] = aux_sym_anonStructType_repeat1,
  [aux_sym_anonStruct_repeat1] = aux_sym_anonStruct_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_templateArguments_repeat1] = aux_sym_templateArguments_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pipe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_pipeline] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_callSig] = {
    .visible = true,
    .named = true,
  },
  [sym_anonStructType] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_valueDef] = {
    .visible = true,
    .named = true,
  },
  [sym_memberInit] = {
    .visible = true,
    .named = true,
  },
  [sym_anonStruct] = {
    .visible = true,
    .named = true,
  },
  [sym_variableDefinition] = {
    .visible = true,
    .named = true,
  },
  [sym_pipelineStage] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__binary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_scopedIdentifierSegment] = {
    .visible = true,
    .named = true,
  },
  [sym_scopedIdentifier] = {
    .visible = true,
    .named = true,
  },
  [sym_templateArguments] = {
    .visible = true,
    .named = true,
  },
  [sym_templateArgument] = {
    .visible = true,
    .named = true,
  },
  [sym_refOp] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipeline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_anonStructType_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_anonStruct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_templateArguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_callSig = 3,
  field_const = 4,
  field_def = 5,
  field_defs = 6,
  field_expressions = 7,
  field_func = 8,
  field_generic = 9,
  field_id = 10,
  field_input = 11,
  field_left = 12,
  field_mut = 13,
  field_output = 14,
  field_refOp = 15,
  field_return = 16,
  field_right = 17,
  field_stages = 18,
  field_type = 19,
  field_value = 20,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_callSig] = "callSig",
  [field_const] = "const",
  [field_def] = "def",
  [field_defs] = "defs",
  [field_expressions] = "expressions",
  [field_func] = "func",
  [field_generic] = "generic",
  [field_id] = "id",
  [field_input] = "input",
  [field_left] = "left",
  [field_mut] = "mut",
  [field_output] = "output",
  [field_refOp] = "refOp",
  [field_return] = "return",
  [field_right] = "right",
  [field_stages] = "stages",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 1},
  [11] = {.index = 15, .length = 1},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 2},
  [15] = {.index = 22, .length = 3},
  [16] = {.index = 25, .length = 1},
  [17] = {.index = 26, .length = 1},
  [18] = {.index = 27, .length = 2},
  [19] = {.index = 29, .length = 1},
  [20] = {.index = 30, .length = 3},
  [21] = {.index = 33, .length = 2},
  [22] = {.index = 35, .length = 2},
  [23] = {.index = 37, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
  [1] =
    {field_id, 0},
  [2] =
    {field_defs, 3},
    {field_id, 1},
  [4] =
    {field_input, 0},
  [5] =
    {field_generic, 1},
    {field_id, 0},
  [7] =
    {field_id, 1},
    {field_mut, 0},
  [9] =
    {field_callSig, 2},
    {field_id, 1},
  [11] =
    {field_body, 0},
  [12] =
    {field_input, 0},
    {field_output, 2},
  [14] =
    {field_mut, 1},
  [15] =
    {field_const, 1},
  [16] =
    {field_id, 1},
    {field_refOp, 0},
  [18] =
    {field_id, 0},
    {field_type, 2},
  [20] =
    {field_body, 1},
    {field_callSig, 0},
  [22] =
    {field_callSig, 2},
    {field_id, 1},
    {field_stages, 4},
  [25] =
    {field_def, 1},
  [26] =
    {field_return, 1},
  [27] =
    {field_args, 1},
    {field_func, 0},
  [29] =
    {field_expressions, 1},
  [30] =
    {field_id, 1},
    {field_mut, 0},
    {field_type, 3},
  [33] =
    {field_left, 0},
    {field_right, 2},
  [35] =
    {field_expressions, 1},
    {field_return, 2},
  [37] =
    {field_id, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '&', 62,
        '(', 44,
        ')', 46,
        '*', 57,
        '+', 54,
        ',', 45,
        '-', 56,
        '/', 58,
        ':', 49,
        ';', 52,
        '<', 60,
        '=', 53,
        '>', 61,
        '[', 40,
      );
      if (lookahead == '\\') SKIP(34);
      if (lookahead == ']') ADVANCE(41);
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(32);
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 'p') ADVANCE(22);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(12);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(10);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(10);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(13);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\r') SKIP(5);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(11);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(11);
      if (lookahead == '\r') SKIP(7);
      END_STATE();
    case 9:
      if (lookahead == '\r') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(76);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    case 10:
      if (lookahead == '&') ADVANCE(62);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '\\') SKIP(4);
      if (lookahead == '{') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 11:
      if (lookahead == '&') ADVANCE(62);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '\\') SKIP(8);
      if (lookahead == 'c') ADVANCE(67);
      if (lookahead == 'm') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        '(', 44,
        ')', 46,
        '*', 57,
        '+', 54,
        ',', 45,
        '-', 55,
        '/', 58,
        ':', 49,
        ';', 52,
        '<', 60,
        '=', 53,
        '>', 61,
      );
      if (lookahead == '\\') SKIP(2);
      if (lookahead == 'l') ADVANCE(65);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 13:
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '\\') SKIP(6);
      if (lookahead == 'm') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 14:
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(77);
      END_STATE();
    case 15:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '/') ADVANCE(75);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 33:
      if (eof) ADVANCE(35);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_pipe);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_mut);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(77);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_const);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(76);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 12},
  [42] = {.lex_state = 12},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 12},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 12},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 10},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 10},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 10},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 10},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 10},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 13},
  [68] = {.lex_state = 11},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 10},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 10},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 10},
  [84] = {.lex_state = 10},
  [85] = {.lex_state = 13},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 10},
  [89] = {.lex_state = 13},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 10},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 10},
  [95] = {.lex_state = 10},
  [96] = {.lex_state = 10},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 10},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 10},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 10},
  [108] = {.lex_state = 10},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_pipe] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(110),
    [sym_module] = STATE(65),
    [aux_sym_source_file_repeat1] = STATE(65),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_mod] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_number,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(48), 1,
      sym_expression,
    STATE(80), 1,
      sym_memberInit,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [46] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(5), 1,
      aux_sym_block_repeat1,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(45), 1,
      sym_expression,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [92] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(28), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(34), 1,
      sym_number,
    STATE(4), 1,
      aux_sym_block_repeat1,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(50), 1,
      sym_expression,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [138] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_block_repeat1,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(41), 1,
      sym_expression,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [184] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(42), 1,
      sym_expression,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [224] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(17), 1,
      sym_expression,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [264] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(22), 1,
      sym_expression,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [304] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(25), 1,
      sym_expression,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [344] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(24), 1,
      sym_expression,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [384] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(19), 1,
      sym_expression,
    STATE(29), 1,
      sym_call,
    STATE(31), 1,
      sym_anonStruct,
    STATE(33), 1,
      sym_scopedIdentifier,
    STATE(34), 7,
      sym_variableDefinition,
      sym__binary_expression,
      sym_assign,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
  [424] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_SLASH,
    ACTIONS(43), 1,
      anon_sym_LT,
    STATE(16), 1,
      sym_templateArguments,
    ACTIONS(39), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [450] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_SLASH,
    ACTIONS(45), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [470] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(49), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [490] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_SLASH,
    ACTIONS(57), 1,
      anon_sym_COLON_COLON,
    ACTIONS(53), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [512] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_SLASH,
    ACTIONS(59), 11,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COLON_COLON,
      anon_sym_GT,
  [532] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_anonStruct,
    ACTIONS(63), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [563] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_COLON,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(77), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [584] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_anonStruct,
    ACTIONS(83), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [605] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_SLASH,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(87), 1,
      anon_sym_COLON,
    STATE(16), 1,
      sym_templateArguments,
    ACTIONS(39), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COLON_COLON,
  [630] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_SLASH,
    ACTIONS(89), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [649] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_anonStruct,
    ACTIONS(93), 8,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(95), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [691] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_anonStruct,
    ACTIONS(99), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [712] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_anonStruct,
    ACTIONS(103), 8,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [735] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_SLASH,
    ACTIONS(105), 10,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_GT,
  [754] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_COLON,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(109), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [775] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_SLASH,
    ACTIONS(115), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [793] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_SLASH,
    ACTIONS(119), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [811] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_SLASH,
    ACTIONS(123), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [829] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_SLASH,
    ACTIONS(119), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [847] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_SLASH,
    ACTIONS(127), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [865] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_SLASH,
    ACTIONS(119), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [883] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_SLASH,
    ACTIONS(119), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [901] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    ACTIONS(131), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_SLASH,
    ACTIONS(135), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [937] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_SLASH,
    ACTIONS(139), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [955] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_SLASH,
    ACTIONS(143), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [973] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_SLASH,
    ACTIONS(147), 9,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [991] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    ACTIONS(153), 1,
      anon_sym_pipe,
    ACTIONS(155), 1,
      anon_sym_func,
    STATE(44), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [1014] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    STATE(28), 1,
      sym_anonStruct,
  [1045] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_anonStruct,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1074] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(153), 1,
      anon_sym_pipe,
    ACTIONS(155), 1,
      anon_sym_func,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    STATE(40), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [1097] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_mod,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    ACTIONS(170), 1,
      anon_sym_pipe,
    ACTIONS(173), 1,
      anon_sym_func,
    STATE(44), 5,
      sym__definition,
      sym_module,
      sym_pipeline,
      sym_function,
      aux_sym_module_repeat1,
  [1120] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_anonStruct,
  [1151] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_AMP,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(26), 1,
      sym_scopedIdentifier,
    STATE(98), 1,
      sym_type,
    STATE(103), 1,
      sym_templateArgument,
    STATE(59), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1177] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    ACTIONS(184), 1,
      anon_sym_RBRACK,
    ACTIONS(186), 1,
      anon_sym_LPAREN,
    STATE(79), 1,
      sym_block,
    STATE(91), 1,
      sym_anonStructType,
    STATE(92), 1,
      sym_callSig,
    STATE(49), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1203] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_anonStruct,
  [1231] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      anon_sym_RBRACK,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    STATE(79), 1,
      sym_block,
    STATE(91), 1,
      sym_anonStructType,
    STATE(92), 1,
      sym_callSig,
    STATE(49), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1257] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_EQ,
    ACTIONS(69), 1,
      anon_sym_PLUS,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym_SLASH,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    STATE(28), 1,
      sym_anonStruct,
  [1285] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      anon_sym_LPAREN,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    STATE(79), 1,
      sym_block,
    STATE(91), 1,
      sym_anonStructType,
    STATE(92), 1,
      sym_callSig,
    STATE(47), 2,
      sym_pipelineStage,
      aux_sym_pipeline_repeat1,
  [1311] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_AMP,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(26), 1,
      sym_scopedIdentifier,
    STATE(87), 1,
      sym_templateArgument,
    STATE(98), 1,
      sym_type,
    STATE(59), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1337] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1363] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_AMP,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(26), 1,
      sym_scopedIdentifier,
    STATE(32), 1,
      sym_type,
    STATE(59), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1399] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_AMP,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(26), 1,
      sym_scopedIdentifier,
    STATE(39), 1,
      sym_type,
    STATE(59), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1422] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 7,
      anon_sym_mod,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_RBRACK,
      anon_sym_func,
      anon_sym_LPAREN,
  [1435] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_AMP,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(21), 1,
      sym_scopedIdentifier,
    STATE(63), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_let,
      sym_identifier,
    ACTIONS(23), 3,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 5,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 5,
      ts_builtin_sym_end,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1490] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_AMP,
    ACTIONS(217), 1,
      sym_identifier,
    STATE(63), 2,
      sym_refOp,
      aux_sym_type_repeat1,
  [1504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1514] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_mod,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
    STATE(66), 2,
      sym_module,
      aux_sym_source_file_repeat1,
  [1528] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(225), 1,
      anon_sym_mod,
    STATE(66), 2,
      sym_module,
      aux_sym_source_file_repeat1,
  [1542] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    ACTIONS(230), 1,
      anon_sym_mut,
    ACTIONS(232), 1,
      sym_identifier,
    STATE(90), 1,
      sym_valueDef,
  [1558] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_mut,
    ACTIONS(236), 1,
      anon_sym_AMP,
    ACTIONS(238), 1,
      anon_sym_const,
    ACTIONS(240), 1,
      sym_identifier,
  [1574] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 4,
      anon_sym_mod,
      anon_sym_RBRACE,
      anon_sym_pipe,
      anon_sym_func,
  [1594] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_anonStruct_repeat1,
  [1607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1616] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
  [1625] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_anonStruct_repeat1,
  [1638] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(261), 1,
      anon_sym_GT,
    STATE(77), 1,
      aux_sym_templateArguments_repeat1,
  [1651] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(15), 1,
      sym_scopedIdentifierSegment,
    STATE(86), 1,
      sym_scopedIdentifier,
  [1664] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_GT,
    STATE(77), 1,
      aux_sym_templateArguments_repeat1,
  [1677] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LPAREN,
    STATE(91), 1,
      sym_anonStructType,
    STATE(105), 1,
      sym_callSig,
  [1690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
  [1699] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_anonStruct_repeat1,
  [1712] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_anonStructType_repeat1,
  [1725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_anonStructType_repeat1,
  [1738] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(281), 1,
      sym_identifier,
    STATE(80), 1,
      sym_memberInit,
  [1751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1760] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_mut,
    ACTIONS(232), 1,
      sym_identifier,
    STATE(100), 1,
      sym_valueDef,
  [1773] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LPAREN,
    STATE(91), 1,
      sym_anonStructType,
    STATE(93), 1,
      sym_callSig,
  [1786] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_GT,
    STATE(75), 1,
      aux_sym_templateArguments_repeat1,
  [1799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
  [1808] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_mut,
    ACTIONS(232), 1,
      sym_identifier,
    STATE(37), 1,
      sym_valueDef,
  [1821] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_anonStructType_repeat1,
  [1834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_DASH_GT,
    ACTIONS(291), 2,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1845] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_block,
  [1855] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    STATE(70), 1,
      sym_block,
  [1865] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(23), 1,
      sym_scopedIdentifierSegment,
  [1875] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
    STATE(102), 1,
      sym_memberInit,
  [1885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 2,
      anon_sym_AMP,
      sym_identifier,
  [1893] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LPAREN,
    STATE(99), 1,
      sym_anonStructType,
  [1903] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 2,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [1919] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 2,
      anon_sym_AMP,
      sym_identifier,
  [1935] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1943] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_identifier,
  [1958] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_LBRACK,
  [1965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_COLON,
  [1972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_identifier,
  [1979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      sym_identifier,
  [1986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
  [1993] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 138,
  [SMALL_STATE(6)] = 184,
  [SMALL_STATE(7)] = 224,
  [SMALL_STATE(8)] = 264,
  [SMALL_STATE(9)] = 304,
  [SMALL_STATE(10)] = 344,
  [SMALL_STATE(11)] = 384,
  [SMALL_STATE(12)] = 424,
  [SMALL_STATE(13)] = 450,
  [SMALL_STATE(14)] = 470,
  [SMALL_STATE(15)] = 490,
  [SMALL_STATE(16)] = 512,
  [SMALL_STATE(17)] = 532,
  [SMALL_STATE(18)] = 563,
  [SMALL_STATE(19)] = 584,
  [SMALL_STATE(20)] = 605,
  [SMALL_STATE(21)] = 630,
  [SMALL_STATE(22)] = 649,
  [SMALL_STATE(23)] = 672,
  [SMALL_STATE(24)] = 691,
  [SMALL_STATE(25)] = 712,
  [SMALL_STATE(26)] = 735,
  [SMALL_STATE(27)] = 754,
  [SMALL_STATE(28)] = 775,
  [SMALL_STATE(29)] = 793,
  [SMALL_STATE(30)] = 811,
  [SMALL_STATE(31)] = 829,
  [SMALL_STATE(32)] = 847,
  [SMALL_STATE(33)] = 865,
  [SMALL_STATE(34)] = 883,
  [SMALL_STATE(35)] = 901,
  [SMALL_STATE(36)] = 919,
  [SMALL_STATE(37)] = 937,
  [SMALL_STATE(38)] = 955,
  [SMALL_STATE(39)] = 973,
  [SMALL_STATE(40)] = 991,
  [SMALL_STATE(41)] = 1014,
  [SMALL_STATE(42)] = 1045,
  [SMALL_STATE(43)] = 1074,
  [SMALL_STATE(44)] = 1097,
  [SMALL_STATE(45)] = 1120,
  [SMALL_STATE(46)] = 1151,
  [SMALL_STATE(47)] = 1177,
  [SMALL_STATE(48)] = 1203,
  [SMALL_STATE(49)] = 1231,
  [SMALL_STATE(50)] = 1257,
  [SMALL_STATE(51)] = 1285,
  [SMALL_STATE(52)] = 1311,
  [SMALL_STATE(53)] = 1337,
  [SMALL_STATE(54)] = 1350,
  [SMALL_STATE(55)] = 1363,
  [SMALL_STATE(56)] = 1386,
  [SMALL_STATE(57)] = 1399,
  [SMALL_STATE(58)] = 1422,
  [SMALL_STATE(59)] = 1435,
  [SMALL_STATE(60)] = 1455,
  [SMALL_STATE(61)] = 1468,
  [SMALL_STATE(62)] = 1479,
  [SMALL_STATE(63)] = 1490,
  [SMALL_STATE(64)] = 1504,
  [SMALL_STATE(65)] = 1514,
  [SMALL_STATE(66)] = 1528,
  [SMALL_STATE(67)] = 1542,
  [SMALL_STATE(68)] = 1558,
  [SMALL_STATE(69)] = 1574,
  [SMALL_STATE(70)] = 1584,
  [SMALL_STATE(71)] = 1594,
  [SMALL_STATE(72)] = 1607,
  [SMALL_STATE(73)] = 1616,
  [SMALL_STATE(74)] = 1625,
  [SMALL_STATE(75)] = 1638,
  [SMALL_STATE(76)] = 1651,
  [SMALL_STATE(77)] = 1664,
  [SMALL_STATE(78)] = 1677,
  [SMALL_STATE(79)] = 1690,
  [SMALL_STATE(80)] = 1699,
  [SMALL_STATE(81)] = 1712,
  [SMALL_STATE(82)] = 1725,
  [SMALL_STATE(83)] = 1738,
  [SMALL_STATE(84)] = 1751,
  [SMALL_STATE(85)] = 1760,
  [SMALL_STATE(86)] = 1773,
  [SMALL_STATE(87)] = 1786,
  [SMALL_STATE(88)] = 1799,
  [SMALL_STATE(89)] = 1808,
  [SMALL_STATE(90)] = 1821,
  [SMALL_STATE(91)] = 1834,
  [SMALL_STATE(92)] = 1845,
  [SMALL_STATE(93)] = 1855,
  [SMALL_STATE(94)] = 1865,
  [SMALL_STATE(95)] = 1875,
  [SMALL_STATE(96)] = 1885,
  [SMALL_STATE(97)] = 1893,
  [SMALL_STATE(98)] = 1903,
  [SMALL_STATE(99)] = 1911,
  [SMALL_STATE(100)] = 1919,
  [SMALL_STATE(101)] = 1927,
  [SMALL_STATE(102)] = 1935,
  [SMALL_STATE(103)] = 1943,
  [SMALL_STATE(104)] = 1951,
  [SMALL_STATE(105)] = 1958,
  [SMALL_STATE(106)] = 1965,
  [SMALL_STATE(107)] = 1972,
  [SMALL_STATE(108)] = 1979,
  [SMALL_STATE(109)] = 1986,
  [SMALL_STATE(110)] = 1993,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifierSegment, 1, 0, 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifierSegment, 1, 0, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArguments, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_templateArguments, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArguments, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_templateArguments, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifier, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifier, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifierSegment, 2, 0, 5),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifierSegment, 2, 0, 5),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 21),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 2, 0, 6),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 2, 0, 6),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 21),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 21),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 12),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 2, 0, 12),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 21),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scopedIdentifier, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scopedIdentifier, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3, 0, 21),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul, 3, 0, 21),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, 0, 21),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 1, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 1, 0, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 18),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 18),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 4, 0, 20),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 4, 0, 20),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variableDefinition, 2, 0, 16),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variableDefinition, 2, 0, 16),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStruct, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonStruct, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_valueDef, 3, 0, 13),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_valueDef, 3, 0, 13),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memberInit, 3, 0, 23),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 17),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 22),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 19),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 5, 0, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 4, 0, 1),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 6, 0, 15),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_refOp, 1, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_refOp, 1, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 5, 0, 7),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipelineStage, 2, 0, 14),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_anonStruct_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_anonStruct_repeat1, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_templateArguments_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_templateArguments_repeat1, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipelineStage, 1, 0, 8),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_anonStructType_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_anonStructType_repeat1, 2, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 3, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonStructType, 4, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callSig, 1, 0, 4),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_refOp, 2, 0, 11),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_templateArgument, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callSig, 3, 0, 9),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_refOp, 2, 0, 10),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [315] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_branescript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
